#### Aspect Keywords from Literature

In [ ]:
staff_keywords = [

    "staff",
    "service",
    "employee",
    "employees",
    "personnel",
    "team",
    "worker",

    "reception",
    "receptionist",
    "front desk",
    "check in",
    "check-in",

    "manager",
    "host",
    "hostess",
    "concierge",

    "friendly",
    "helpful",
    "welcoming",
    "professional",
    "courteous",

    "customer service",
    "hospitality"
]

In [ ]:
cleanliness_keywords = [

    "clean",
    "cleanliness",
    "spotless",
    "tidy",

    "dirty",
    "messy",
    "dust",
    "dusty",

    "hygiene",
    "sanitary",

    "bathroom",
    "toilet",
    "shower",

    "bed",
    "bedsheets",
    "linen",
    "towel",

    "stain",
    "smell",
    "odour",
    "odor"
]

In [ ]:
location_keywords = [

    "location",
    "distance",

    "city centre",
    "city center",
    "downtown",
    "city",
    "center",
    "centre",

    "airport",
    "station",
    "bus",

    "walking distance",
    "nearby",

    "beach",
    "sea",
    "view",
    "lake",
    "pool",
    "ocean",
    "waterfall",

    "transport",
    "access",

    "central",
    "convenient",

    "parking",
    "park",
    "mall",
    "shopping",
]

In [ ]:
value_keywords = [

    "value",
    "value for money",

    "price",
    "pricing",
    "cost",

    "expensive",
    "cheap",

    "affordable",
    "budget",

    "worth",
    "worthwhile",

    "overpriced",
    "reasonable",

    "money",
    "paid",
    "rate"
]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

processed_path = "/content/drive/MyDrive/Colab Notebooks/Irish Hotel Reviews/Dataset/processed/irish_hotel_reviews_processed.csv"

df = pd.read_csv(processed_path)

print(df.shape)
print(df.columns)

(13294, 13)
Index(['review_id', 'review_text', 'overall_rating', 'hotel_name', 'county',
       'trip_type', 'language', 'clean_review', 'word_count', 'sentiment',
       'anonymized_review', 'final_review', 'clean_review_ml'],
      dtype='object')

#### Generate candidate keywords using TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

vectorizer = TfidfVectorizer(
    max_features=1000,
    stop_words='english',
    ngram_range=(1,2)
)

X = vectorizer.fit_transform(df["clean_review_ml"])

terms = vectorizer.get_feature_names_out()

tfidf_scores = X.sum(axis=0).A1

tfidf_df = pd.DataFrame({
    "term": terms,
    "score": tfidf_scores
})

tfidf_df = tfidf_df.sort_values(
    by="score",
    ascending=False
)

print(tfidf_df.head(100))

       term       score
416   hotel  825.506130
623  person  788.579449
719    room  680.098653
804   staff  665.199572
366   great  620.997009
..      ...         ...
825    star  114.029365
559  minute  113.818496
940    view  113.793169
204   didnt  113.158666
155    come  112.427519

[100 rows x 2 columns]

In [ ]:
tfidf_df.to_csv(
    "/content/drive/MyDrive/Colab Notebooks/Irish Hotel Reviews/Dataset/candidate_keywords_tfidf.csv",
    index=False
)

#### Build Word2Vec Model

In [ ]:
pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 52.6 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
# train the model
from gensim.models import Word2Vec

sentences = [
    review.split()
    for review in df["clean_review_ml"]
]

model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=5,
    workers=4
)

In [ ]:
model.save("/content/drive/MyDrive/Colab Notebooks/Irish Hotel Reviews/Dataset/word2vec_model/hotel_reviews_word2vec.model")

In [ ]:
model.wv.most_similar(
    "clean",
    topn=20
)

[('spotless', 0.921722412109375),
 ('spacious', 0.8805510997772217),
 ('tidy', 0.8728525042533875),
 ('spotlessly', 0.8556082248687744),
 ('modern', 0.846021831035614),
 ('stylish', 0.8404029607772827),
 ('cozy', 0.8387376666069031),
 ('nicely', 0.8371930718421936),
 ('appointed', 0.8321655988693237),
 ('bright', 0.8193922638893127),
 ('cosy', 0.8128646016120911),
 ('immaculate', 0.8098204135894775),
 ('equipped', 0.8041330575942993),
 ('maintained', 0.7992038130760193),
 ('quiet', 0.7984271049499512),
 ('decorated', 0.7913798093795776),
 ('decor', 0.7851454019546509),
 ('designed', 0.7839025259017944),
 ('sized', 0.7675423622131348),
 ('large', 0.7536672949790955)]

#### Seed words

##### Staff

In [ ]:
staff_seed_words = [
    "staff",
    "service",
    "reception"
]

In [ ]:
cleanliness_seed_words = [
    "clean",
    "cleanliness",
    "dirty"
]

In [ ]:
location_seed_words = [
    "location",
    "airport",
    "centre"
]

In [ ]:
value_seed_words = [
    "value",
    "price",
    "cost"
]

In [ ]:
import pandas as pd

staff_results = []

for word in staff_seed_words:
    results = model.wv.most_similar(word, topn=20)

    for discovered_word, similarity in results:
        staff_results.append({
            "aspect":"staff",
            "seed_word": word,
            "discovered_word": discovered_word,
            "similarity": similarity
        })

staff_df = pd.DataFrame(staff_results)

print(staff_df)

   aspect  seed_word discovered_word  similarity
0   staff      staff       efficient    0.693065
1   staff      staff   knowledgeable    0.690846
2   staff      staff    professional    0.678560
3   staff      staff          polite    0.669352
4   staff      staff          chatty    0.664398
5   staff      staff       extremely    0.653992
6   staff      staff       christina    0.646219
7   staff      staff           super    0.645593
8   staff      staff   accommodating    0.643687
9   staff      staff       courteous    0.642545
10  staff      staff        employee    0.631708
11  staff      staff      incredibly    0.627253
12  staff      staff    approachable    0.623318
13  staff      staff   exceptionally    0.621951
14  staff      staff    particularly    0.619675
15  staff      staff        everyone    0.608271
16  staff      staff      personable    0.607538
17  staff      staff        freindly    0.605972
18  staff      staff            kind    0.605677
19  staff      staff        cheerful    0.605440
20  staff    service          server    0.681753
21  staff    service         alberto    0.680115
22  staff    service          waiter    0.642734
23  staff    service        employee    0.631559
24  staff    service    consistently    0.628784
25  staff    service    presentation    0.620715
26  staff    service      personable    0.615030
27  staff    service     hospitality    0.610932
28  staff    service       bartender    0.610269
29  staff    service            host    0.609317
30  staff    service      particular    0.609054
31  staff    service           emily    0.600174
32  staff    service    knowledgable    0.598571
33  staff    service          prompt    0.597514
34  staff    service       attention    0.596990
35  staff    service         awesome    0.591218
36  staff    service        customer    0.590986
37  staff    service         focused    0.589444
38  staff    service     outstanding    0.587574
39  staff    service           skill    0.585978
40  staff  reception    receptionist    0.849658
41  staff  reception            lady    0.830934
42  staff  reception       gentleman    0.826680
43  staff  reception           young    0.825604
44  staff  reception         greeted    0.822802
45  staff  reception             met    0.820696
46  staff  reception         doorman    0.812178
47  staff  reception        greeting    0.808210
48  staff  reception           dealt    0.805146
49  staff  reception       concierge    0.804329
50  staff  reception             man    0.785845
51  staff  reception           named    0.779315
52  staff  reception          porter    0.778114
53  staff  reception        beatrice    0.776697
54  staff  reception           clerk    0.772267
55  staff  reception           aoife    0.767047
56  staff  reception            kind    0.759944
57  staff  reception        checking    0.753097
58  staff  reception          cennet    0.750522
59  staff  reception           chloe    0.750294

In [ ]:
import pandas as pd

cleanliness_results = []

for word in cleanliness_seed_words:
    results = model.wv.most_similar(word, topn=20)

    for discovered_word, similarity in results:
        cleanliness_results.append({
            "aspect":"cleanliness",
            "seed_word": word,
            "discovered_word": discovered_word,
            "similarity": similarity
        })

cleanliness_df = pd.DataFrame(cleanliness_results)

print(cleanliness_df)

         aspect    seed_word discovered_word  similarity
0   cleanliness        clean        spotless    0.921722
1   cleanliness        clean        spacious    0.880551
2   cleanliness        clean            tidy    0.872853
3   cleanliness        clean      spotlessly    0.855608
4   cleanliness        clean          modern    0.846022
5   cleanliness        clean         stylish    0.840403
6   cleanliness        clean            cozy    0.838738
7   cleanliness        clean          nicely    0.837193
8   cleanliness        clean       appointed    0.832166
9   cleanliness        clean          bright    0.819392
10  cleanliness        clean            cosy    0.812865
11  cleanliness        clean      immaculate    0.809820
12  cleanliness        clean        equipped    0.804133
13  cleanliness        clean      maintained    0.799204
14  cleanliness        clean           quiet    0.798427
15  cleanliness        clean       decorated    0.791380
16  cleanliness        clean           decor    0.785145
17  cleanliness        clean        designed    0.783903
18  cleanliness        clean           sized    0.767542
19  cleanliness        clean           large    0.753667
20  cleanliness  cleanliness         comfort    0.870111
21  cleanliness  cleanliness            high    0.861396
22  cleanliness  cleanliness      impeccable    0.852025
23  cleanliness  cleanliness         quality    0.851755
24  cleanliness  cleanliness        standard    0.827048
25  cleanliness  cleanliness   accommodation    0.809905
26  cleanliness  cleanliness     beautifully    0.808646
27  cleanliness  cleanliness         highest    0.791116
28  cleanliness  cleanliness         amenity    0.790033
29  cleanliness  cleanliness      impressive    0.786958
30  cleanliness  cleanliness      immaculate    0.775059
31  cleanliness  cleanliness           decor    0.772052
32  cleanliness  cleanliness       luxurious    0.768194
33  cleanliness  cleanliness      spotlessly    0.763960
34  cleanliness  cleanliness        designed    0.758743
35  cleanliness  cleanliness      impeccably    0.753845
36  cleanliness  cleanliness         elegant    0.753811
37  cleanliness  cleanliness       exquisite    0.745018
38  cleanliness  cleanliness    immaculately    0.744123
39  cleanliness  cleanliness   exceptionally    0.736706
40  cleanliness        dirty        replaced    0.964816
41  cleanliness        dirty             tap    0.958352
42  cleanliness        dirty        properly    0.957378
43  cleanliness        dirty             fan    0.957189
44  cleanliness        dirty            hair    0.956238
45  cleanliness        dirty         clothes    0.953864
46  cleanliness        dirty            wash    0.952996
47  cleanliness        dirty             ice    0.951364
48  cleanliness        dirty         heating    0.950099
49  cleanliness        dirty          toilet    0.949391
50  cleanliness        dirty          broken    0.948909
51  cleanliness        dirty            heat    0.945730
52  cleanliness        dirty           loose    0.942517
53  cleanliness        dirty              ac    0.938429
54  cleanliness        dirty            tiny    0.935908
55  cleanliness        dirty           light    0.935269
56  cleanliness        dirty            type    0.934227
57  cleanliness        dirty          mirror    0.930207
58  cleanliness        dirty            sink    0.929858
59  cleanliness        dirty           brush    0.929578

In [ ]:
import pandas as pd

cleanliness_results = []

for word in cleanliness_seed_words:
    results = model.wv.most_similar(word, topn=20)

    for discovered_word, similarity in results:
        cleanliness_results.append({
            "aspect":"cleanliness",
            "seed_word": word,
            "discovered_word": discovered_word,
            "similarity": similarity
        })

cleanliness_df = pd.DataFrame(cleanliness_results)

print(cleanliness_df)

         aspect    seed_word discovered_word  similarity
0   cleanliness        clean        spotless    0.921722
1   cleanliness        clean        spacious    0.880551
2   cleanliness        clean            tidy    0.872853
3   cleanliness        clean      spotlessly    0.855608
4   cleanliness        clean          modern    0.846022
5   cleanliness        clean         stylish    0.840403
6   cleanliness        clean            cozy    0.838738
7   cleanliness        clean          nicely    0.837193
8   cleanliness        clean       appointed    0.832166
9   cleanliness        clean          bright    0.819392
10  cleanliness        clean            cosy    0.812865
11  cleanliness        clean      immaculate    0.809820
12  cleanliness        clean        equipped    0.804133
13  cleanliness        clean      maintained    0.799204
14  cleanliness        clean           quiet    0.798427
15  cleanliness        clean       decorated    0.791380
16  cleanliness        clean           decor    0.785145
17  cleanliness        clean        designed    0.783903
18  cleanliness        clean           sized    0.767542
19  cleanliness        clean           large    0.753667
20  cleanliness  cleanliness         comfort    0.870111
21  cleanliness  cleanliness            high    0.861396
22  cleanliness  cleanliness      impeccable    0.852025
23  cleanliness  cleanliness         quality    0.851755
24  cleanliness  cleanliness        standard    0.827048
25  cleanliness  cleanliness   accommodation    0.809905
26  cleanliness  cleanliness     beautifully    0.808646
27  cleanliness  cleanliness         highest    0.791116
28  cleanliness  cleanliness         amenity    0.790033
29  cleanliness  cleanliness      impressive    0.786958
30  cleanliness  cleanliness      immaculate    0.775059
31  cleanliness  cleanliness           decor    0.772052
32  cleanliness  cleanliness       luxurious    0.768194
33  cleanliness  cleanliness      spotlessly    0.763960
34  cleanliness  cleanliness        designed    0.758743
35  cleanliness  cleanliness      impeccably    0.753845
36  cleanliness  cleanliness         elegant    0.753811
37  cleanliness  cleanliness       exquisite    0.745018
38  cleanliness  cleanliness    immaculately    0.744123
39  cleanliness  cleanliness   exceptionally    0.736706
40  cleanliness        dirty        replaced    0.964816
41  cleanliness        dirty             tap    0.958352
42  cleanliness        dirty        properly    0.957378
43  cleanliness        dirty             fan    0.957189
44  cleanliness        dirty            hair    0.956238
45  cleanliness        dirty         clothes    0.953864
46  cleanliness        dirty            wash    0.952996
47  cleanliness        dirty             ice    0.951364
48  cleanliness        dirty         heating    0.950099
49  cleanliness        dirty          toilet    0.949391
50  cleanliness        dirty          broken    0.948909
51  cleanliness        dirty            heat    0.945730
52  cleanliness        dirty           loose    0.942517
53  cleanliness        dirty              ac    0.938429
54  cleanliness        dirty            tiny    0.935908
55  cleanliness        dirty           light    0.935269
56  cleanliness        dirty            type    0.934227
57  cleanliness        dirty          mirror    0.930207
58  cleanliness        dirty            sink    0.929858
59  cleanliness        dirty           brush    0.929578

In [ ]:
import pandas as pd

location_results = []

for word in location_seed_words:
    results = model.wv.most_similar(word, topn=20)

    for discovered_word, similarity in results:
        location_results.append({
            "aspect":"location",
            "seed_word": word,
            "discovered_word": discovered_word,
            "similarity": similarity
        })

location_df = pd.DataFrame(location_results)

print(location_df)

      aspect seed_word discovered_word  similarity
0   location  location         located    0.742088
1   location  location            spot    0.726551
2   location  location       exploring    0.726237
3   location  location        situated    0.704982
4   location  location         central    0.701141
5   location  location            base    0.698682
6   location  location          centre    0.693589
7   location  location      convenient    0.692217
8   location  location          center    0.690344
9   location  location       centrally    0.674815
10  location  location           heart    0.673085
11  location  location    conveniently    0.669460
12  location  location           close    0.667245
13  location  location            town    0.664436
14  location  location          dublin    0.653359
15  location  location      attraction    0.645925
16  location  location            city    0.645026
17  location  location           arena    0.639297
18  location  location        shopping    0.638082
19  location  location     sightseeing    0.636943
20  location   airport         shuttle    0.959588
21  location   airport             bus    0.953737
22  location   airport            stop    0.938537
23  location   airport            dart    0.913763
24  location   airport             hop    0.902981
25  location   airport       transport    0.893540
26  location   airport           right    0.888206
27  location   airport           train    0.882824
28  location   airport            ride    0.875838
29  location   airport        downtown    0.867987
30  location   airport            road    0.866076
31  location   airport            tram    0.861704
32  location   airport         express    0.850706
33  location   airport           handy    0.848132
34  location   airport  transportation    0.847018
35  location   airport           arena    0.846710
36  location   airport         transit    0.844834
37  location   airport             rds    0.842807
38  location   airport        terminal    0.841826
39  location   airport           meter    0.841000
40  location    centre          center    0.952652
41  location    centre       exploring    0.862974
42  location    centre           close    0.856320
43  location    centre         explore    0.848613
44  location    centre           heart    0.848194
45  location    centre        walkable    0.845626
46  location    centre        situated    0.842846
47  location    centre         central    0.824729
48  location    centre         trinity    0.812758
49  location    centre      convenient    0.807272
50  location    centre         located    0.801327
51  location    centre            town    0.801013
52  location    centre            near    0.797270
53  location    centre          stroll    0.797084
54  location    centre        downtown    0.791644
55  location    centre      everywhere    0.788241
56  location    centre      attraction    0.786552
57  location    centre       transport    0.783006
58  location    centre           short    0.781071
59  location    centre    conveniently    0.776708

In [ ]:
import pandas as pd

value_results = []

for word in value_seed_words:
    results = model.wv.most_similar(word, topn=20)

    for discovered_word, similarity in results:
        value_results.append({
            "aspect":"value",
            "seed_word": word,
            "discovered_word": discovered_word,
            "similarity": similarity
        })

value_df = pd.DataFrame(value_results)

print(value_df)

   aspect seed_word discovered_word  similarity
0   value     value           money    0.826807
1   value     value           price    0.777317
2   value     value      reasonable    0.712922
3   value     value         overall    0.698216
4   value     value            rate    0.669139
5   value     value          priced    0.649030
6   value     value        location    0.634024
7   value     value         quality    0.632414
8   value     value      reasonably    0.632087
9   value     value         amenity    0.629738
10  value     value           liked    0.608518
11  value     value     welllocated    0.602327
12  value     value   accommodation    0.601532
13  value     value           range    0.593455
14  value     value           worth    0.586040
15  value     value     considering    0.583582
16  value     value      affordable    0.579804
17  value     value       heartbeat    0.567982
18  value     value     cleanliness    0.566824
19  value     value        facility    0.566265
20  value     price       expensive    0.868201
21  value     price      reasonable    0.868023
22  value     price           money    0.827930
23  value     price     considering    0.786221
24  value     price           value    0.777317
25  value     price            rate    0.755486
26  value     price          decent    0.748238
27  value     price        compared    0.742044
28  value     price          expect    0.740634
29  value     price      acceptable    0.734645
30  value     price           offer    0.731626
31  value     price        expected    0.725525
32  value     price         average    0.711823
33  value     price            fine    0.708073
34  value     price      reasonably    0.695083
35  value     price          priced    0.687026
36  value     price        negative    0.684004
37  value     price         bargain    0.671071
38  value     price       otherwise    0.665971
39  value     price           worth    0.661040
40  value      cost          amount    0.937935
41  value      cost           maybe    0.930726
42  value      cost           avoid    0.930466
43  value      cost            paid    0.927388
44  value      cost      disturbing    0.926848
45  value      cost             tho    0.925037
46  value      cost         charged    0.923766
47  value      cost         website    0.922433
48  value      cost        annoying    0.921806
49  value      cost           tired    0.920145
50  value      cost         usually    0.918270
51  value      cost       expecting    0.918082
52  value      cost            thin    0.916360
53  value      cost           heard    0.913503
54  value      cost            euro    0.913224
55  value      cost          unable    0.913042
56  value      cost    occasionally    0.912310
57  value      cost       mcdonalds    0.912303
58  value      cost           cheap    0.912256
59  value      cost           drain    0.910959

In [ ]:
combined_df = pd.concat(
    [staff_df, cleanliness_df, location_df, value_df],
    axis=0,          # stack rows (default)
    ignore_index=True
)

print(combined_df.head())

  aspect seed_word discovered_word  similarity
0  staff     staff       efficient    0.693065
1  staff     staff   knowledgeable    0.690846
2  staff     staff    professional    0.678560
3  staff     staff          polite    0.669352
4  staff     staff          chatty    0.664398

In [ ]:
combined_df.shape

(240, 4)

In [ ]:
combined_df = (
    combined_df
    .sort_values("similarity", ascending=False)
    .drop_duplicates(subset="discovered_word")
    .reset_index(drop=True)
)

In [ ]:
combined_df.head()

        aspect seed_word discovered_word  similarity
0  cleanliness     dirty        replaced    0.964816
1     location   airport         shuttle    0.959588
2  cleanliness     dirty             tap    0.958352
3  cleanliness     dirty        properly    0.957378
4  cleanliness     dirty             fan    0.957189

In [ ]:
combined_df.to_csv(
    "aspect_expansion_table.csv",
    index=False
)

In [ ]:
staff_word2vec_keywords = [
    "receptionist",
    "gentleman",
    "doorman",
    "young",
    "man",
    "concierge",
    "checking",
    "lady",
    "dealt",
    "greeted",
    "chatty",
    "met",
    "kind",
    "greeting",
    "courteous",
    "checkin",
    "server",
    "polite",
    "efficient",
    "incredibly",
    "alberto",
    "extremely",
    "approachable",
    "waiter",
    "employee",
    "knowledgeable",
    "professional",
    "consistently",
    "attention",
    "presentation",
    "particular",
    "encountered",
    "job",
    "everyone",
    "exceptionally",
    "bartender",
    "hospitality",
    "smiley",
    "prompt",
    "cleanliness",
    "host",
    "accommodating",
    "top",
    "customer",
    "team",
    "personable"
]

In [ ]:
cleanliness_word2vec_keywords = [
    "fan",
    "hair",
    "toilet",
    "tap",
    "light",
    "heat",
    "wash",
    "broken",
    "carpet",
    "mirror",
    "sink",
    "clothes",
    "properly",
    "ac",
    "curtain",
    "spotless",
    "spacious",
    "tidy",
    "comfort",
    "spotlessly",
    "high",
    "quality",
    "cozy",
    "modern",
    "bright",
    "standard",
    "amenity",
    "cosy",
    "equipped",
    "immaculate",
    "decor",
    "maintained",
    "elegant",
    "comfy",
    "luxurious",
    "interior",
    "impressive",
    "accommodation",
    "importantly",
    "wellappointed",
    "aesthetically",
]

In [ ]:
location_word2vec_keywords = [
    "center",
    "shuttle",
    "bus",
    "stop",
    "dart",
    "hop",
    "exploring",
    "tram",
    "train",
    "handy",
    "right",
    "positioned",
    "ride",
    "transport",
    "across",
    "downtown",
    "explore",
    "transportation",
    "sight",
    "road",
    "arena",
    "close",
    "walkable",
    "reach",
    "near",
    "situated",
    "town",
    "central",
    "heart",
    "attraction",
    "stroll",
    "stadium",
    "shopping",
    "convenient",
    "everywhere",
    "located",
    "base",
    "spot",
    "centre",
    "centrally",
    "city",
    "walkability",
]

In [ ]:
value_word2vec_keywords = [
    "avoid",
    "paying",
    "laundry",
    "tired",
    "slightly",
    "least",
    "worried",
    "vent",
    "reasonable",
    "expensive",
    "money",
    "rate",
    "considering",
    "expect",
    "offer",
    "price",
    "value",
    "expected",
    "fine",
    "decent",
    "priced",
    "overall",
    "outrageous",
    "compared",
    "average",
    "pricey",
    "reasonably",
    "choice",
    "range",
    "picky",
    "facility",
    "welllocated",
    "variety",
    "size"
]

In [ ]:
staff_combined = (
    pd.Series(staff_keywords + staff_word2vec_keywords)
    .drop_duplicates()
    .tolist()
)

staff_combined

['staff',
 'service',
 'employee',
 'employees',
 'personnel',
 'team',
 'worker',
 'reception',
 'receptionist',
 'front desk',
 'check in',
 'check-in',
 'manager',
 'host',
 'hostess',
 'concierge',
 'friendly',
 'helpful',
 'welcoming',
 'professional',
 'courteous',
 'customer service',
 'hospitality',
 'gentleman',
 'doorman',
 'young',
 'man',
 'checking',
 'lady',
 'dealt',
 'greeted',
 'chatty',
 'met',
 'kind',
 'greeting',
 'checkin',
 'server',
 'polite',
 'efficient',
 'incredibly',
 'alberto',
 'extremely',
 'approachable',
 'waiter',
 'knowledgeable',
 'consistently',
 'attention',
 'presentation',
 'particular',
 'encountered',
 'job',
 'everyone',
 'exceptionally',
 'bartender',
 'smiley',
 'prompt',
 'cleanliness',
 'accommodating',
 'top',
 'customer',
 'personable']

In [ ]:
import json

# Map aspect name -> list pair
aspect_sources = {
    "staff": [staff_keywords, staff_word2vec_keywords],
    "cleanliness": [cleanliness_keywords, cleanliness_word2vec_keywords],
    "location": [location_keywords, location_word2vec_keywords],
    "value": [value_keywords, value_word2vec_keywords],
}

# Combine and deduplicate
aspect_dictionary = {
    aspect: (
        pd.Series(lst1 + lst2)
        .drop_duplicates()
        .tolist()
    )
    for aspect, (lst1, lst2) in aspect_sources.items()
}

# Save to JSON
with open("aspect_dictionary.json", "w", encoding="utf-8") as f:
    json.dump(aspect_dictionary, f, indent=4, ensure_ascii=False)

print("Saved to aspect_dictionary.json")

Saved to aspect_dictionary.json

#### Create Aspect Dictionary Pipeline

In [ ]:
review = "Staff were extremely helpful. The room was spotless. Location was a little far from town."

In [ ]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.tokenize import sent_tokenize

sentences = sent_tokenize(review)

In [ ]:
sentences

['Staff were extremely helpful.',
 'The room was spotless.',
 'Location was a little far from town.']

In [ ]:
import json

with open("aspect_dictionary.json") as f:
    aspect_dict = json.load(f)

In [ ]:
def detect_aspects(sentence):

    sentence_lower = sentence.lower()

    found_aspects = []

    for aspect, keywords in aspect_dict.items():

        for keyword in keywords:

            if keyword in sentence_lower:

                found_aspects.append(aspect)

                break

    return found_aspects

In [ ]:
sentence = "Staff were extremely friendly"

print(detect_aspects(sentence))

['staff']

In [ ]:
review = """
Our stay in the hotel was a real pleasure in this hotel.
Thanks to Elena in reception that suggested us a very good places to visit the town.
"""

In [ ]:
records = []

sentences = sent_tokenize(review)

for sentence in sentences:

    aspects = detect_aspects(sentence)

    for aspect in aspects:

        records.append({
            "aspect": aspect,
            "text": sentence
        })

In [ ]:
records

[{'aspect': 'staff',
  'text': 'Thanks to Elena in reception that suggested us a very good places to visit the town.'},
 {'aspect': 'cleanliness',
  'text': 'Thanks to Elena in reception that suggested us a very good places to visit the town.'},
 {'aspect': 'location',
  'text': 'Thanks to Elena in reception that suggested us a very good places to visit the town.'}]

#### process entire dataset

In [ ]:
aspect_records = []

for idx, row in df.iterrows():

    review_id = row["review_id"]

    review = row["final_review"]

    sentences = sent_tokenize(review)

    for sentence in sentences:

        aspects = detect_aspects(sentence)

        for aspect in aspects:

            aspect_records.append({

                "review_id": review_id,

                "aspect": aspect,

                "aspect_text": sentence
            })

In [ ]:
aspect_df = pd.DataFrame(
    aspect_records
)

In [ ]:
aspect_df.head()

    review_id       aspect                                        aspect_text
0  1062725118     location                   This hotel was a great location.
1  1062725118  cleanliness  The rooms were spacious for Europe, and it had...
2  1062725118  cleanliness  The vending machine was out of order, there is...
3  1062725118        staff  So plan to stop at the local food shops for wa...
4  1062725118     location  So plan to stop at the local food shops for wa...

In [ ]:
aspect_df.shape

(69520, 3)

In [ ]:
aspect_df.to_csv(
    "rule_based_aspects.csv",
    index=False
)

#### Create a dataset for manual annotation

In [ ]:
sample_df = df.sample(
    500,
    random_state=42
)

In [ ]:
sample_df.to_csv(
    "manual_annotation.csv",
    index=False
)